# key? 32byte (256bit)
jwt:
  secretKey: 12345678901234567890123456789012
  refreshKey: 12345678901234567890123456789012




spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
